"""Rechange

Revision ID: 8b508b84b986
Revises: 58d03f21d141
Create Date: 2022-04-10 18:13:49.101335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b508b84b986'
down_revision = '58d03f21d141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('street_sender', sa.String(length=255), nullable=True))
    op.drop_column('orders', 'steet_sender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('steet_sender', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('orders', 'street_sender')
    # ### end Alembic commands ###
