"""create user

Revision ID: d6155355b1ba
Revises: 
Create Date: 2022-02-20 21:05:29.986035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6155355b1ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('namber_phone', sa.String(length=13), nullable=True),
    sa.Column('type_wantazy', sa.String(length=150), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.String(length=6), nullable=True),
    sa.Column('date_dostavki', sa.String(length=20), nullable=True),
    sa.Column('city_start', sa.String(length=150), nullable=True),
    sa.Column('city_finish', sa.String(length=150), nullable=True),
    sa.Column('street_start', sa.String(length=150), nullable=True),
    sa.Column('number_home_start', sa.Integer(), nullable=True),
    sa.Column('street_finish', sa.String(length=150), nullable=True),
    sa.Column('number_home_finish', sa.Integer(), nullable=True),
    sa.Column('pay_method', sa.String(length=50), nullable=True),
    sa.Column('isActive', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['city_finish'], ['citys.id'], ),
    sa.ForeignKeyConstraint(['city_start'], ['citys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('citys')
    # ### end Alembic commands ###
