"""Create Feedback

Revision ID: dc932cf451a2
Revises: d6155355b1ba
Create Date: 2022-02-22 13:49:09.983469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc932cf451a2'
down_revision = 'd6155355b1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pib', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=155), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.Column('ts_feedback', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('citys')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('namber_phone', sa.VARCHAR(length=13), nullable=True),
    sa.Column('type_wantazy', sa.VARCHAR(length=150), nullable=True),
    sa.Column('weight', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('time', sa.VARCHAR(length=6), nullable=True),
    sa.Column('date_dostavki', sa.VARCHAR(length=20), nullable=True),
    sa.Column('city_start', sa.VARCHAR(length=150), nullable=True),
    sa.Column('city_finish', sa.VARCHAR(length=150), nullable=True),
    sa.Column('street_start', sa.VARCHAR(length=150), nullable=True),
    sa.Column('number_home_start', sa.INTEGER(), nullable=True),
    sa.Column('street_finish', sa.VARCHAR(length=150), nullable=True),
    sa.Column('number_home_finish', sa.INTEGER(), nullable=True),
    sa.Column('pay_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('isActive', sa.VARCHAR(length=60), nullable=True),
    sa.ForeignKeyConstraint(['city_finish'], ['citys.id'], ),
    sa.ForeignKeyConstraint(['city_start'], ['citys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('region', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feedback')
    # ### end Alembic commands ###
